# dev.yaml 开发环境的配置
env_config:
  base_url: https://litemall.hogwarts.ceshiren.com/
db_config:
  host: httpbin.ceshiren.com
  username: xxxx
  password: xxxx
redis_config:
  host: httpbin.ceshiren.com
  port: 8100